### ISSUE TITLE
Obsługa filtrów na zleceniach/zamówieniach (order)

### ISSUE THREAD

**Issue by GringoXY** [THD-C/DB_Manager#26]
W operacji typu HTTP GET do pobierania wielu zamówień dobrze będzie dodać filtry:
* `wallet_id` -> na jakim portfelu została wykonana operacja (czy na portfelu walutowym PLN/EUR itp. czy na portfelu krypto BTC/ETH). Jeśli `wallet_id` ma wartośc `null` to filtrujemy wszystko (działa to tak jakbyśmy w ogóle nie podali filtru). Przykład zapytania SQL, który pogląd jak to ma działać:
```sql
select *
from table
where
  user_id = @user_id
  and (@provided_wallet_id is null or wallet_id = @provided_wallet_id)
```
* `side` -> kierunek - buy/sell (Jeśli `side` ma wartośc `null` to filtrujemy wszystko (działa to tak jakbyśmy w ogóle nie podali filtru). Przykład zapytania SQL, który pogląd jak to ma działać:
```sql
select *
from table
where
  user_id = @user_id
  and (@provided_side is null or side = @provided_side)
```
* `status` -> jaki jest aktualny status zamówienia (Jeśli `status` ma wartośc `null` to filtrujemy wszystko (działa to tak jakbyśmy w ogóle nie podali filtru). Przykład zapytania SQL, który pogląd jak to ma działać:
```sql
select *
from table
where
  user_id = @user_id
  and (@provided_status is null or status = @provided_status)
```

Filtry głównie potrzebne do:
* wyświetlania historii zamówień na widoku giełdy (strona [stock](/stock)) oraz przy wyświetlaniu historii w ramach danego portfela (strona [profile](/profile)),
* możliwość szybszego odnalezienia zamówienia w ramach danego krypto i jego anulowania.

**Comment by GringoXY** [comment]
@rukaSUKII 
@StanislawHornaGitHub

**Comment by StanislawHornaGitHub** [comment]
Każdy endpoint dodatkowo powinien zawierać user_id jako filtr
