### ISSUE TITLE
Autoryzowanie użytkownika podczas logowania z pomocą maila lub username

### ISSUE THREAD

**Issue by rukaSUKII** [THD-C/DB_Manager#3]
W service User.Authenticate dodanie weryfikacji użytkownika również poprzez username na podstawie pola email z message AuthUser.
(W polu może się znajdować się wartość do pola email lub username znajdujących się w bazie danych). Zmiana schematu message AuthUser nie jest konieczna.
Dzięki temu użytkownik nie będzie ograniczony do podania emaila w oknie logowania, aby uzyskać dostęp do systemu.

**Comment by StanislawHornaGitHub** [comment]
@rukaSUKII message do logowania ma miec 3 pola? Tj. Username, email, password?

**Comment by rukaSUKII** [comment]
@StanislawHornaGitHub 
Wydaje mi się, że nie jest to konieczne. W dialogu logowania po stronie Frontend będą tylko dwa pola input email/username oraz hasło.
W sytuacji gdyby były 3 pola w message do grpc musiałaby być 3 pola w oknie logowania.
Wydaje mi się że wystarczy to rozwiązać w klauzuli where email==message.email or username==message.email po stronie bazy. Komunikacja sama nie będzie przekombinowana wtedy

**Comment by StanislawHornaGitHub** [comment]
@rukaSUKII spoko, natomiast żeby nie wprowadzać zamieszania, zmieniłbym nazwę pola w message z email na "login" - takiego pola nie mamy i raczej nie bedziemy mieli w DB, wiec nie będzie konsternacji co jak działa i dlaczego

**Comment by rukaSUKII** [comment]
@StanislawHornaGitHub celna uwaga - jestem za
