### ISSUE TITLE
Dodanie serwisu dotyczącego operacji na danych usera

### ISSUE THREAD

**Issue by rukaSUKII** [THD-C/DB_Manager#8]
Potrzebne będą metody do umożliwienia użytkownikowi edycję danych jego konta tj.
password, email z tabeli user (username raczej bym ominął)
wszystkie pola z tabeli user_detail

Proponuję to zrobić dwoma metodami, ale to już zależy od prostoty takiej operacji do wykonania po stronie DB_Manager - dla mnie to żaden problem, żeby była jedna. W messageRequest uwzględniony również user_id z tabeli user.

Dodatkowo umożliwiłbym całkowite usunięcie konta z bazy w tym serwisie, gdzie na podstawie user_id usuwane są wszystkie rekordy jakie występują w bazie dla danego klienta. Trzeba jeszcze uwzględnić, że mogą być wiszące ordery w order_service, więc takie pending ordery też by trzeba usunąć, bo mogą potem powstać problemy, gdy zostanie wykonany order, a takie dane w bazie nie istnieją

@StanislawHornaGitHub @GringoXY Proszę o wypowiedzenie się w tym temacie.

**Comment by StanislawHornaGitHub** [comment]
@rukaSUKII 
## Modyfikacja danych
Dla mnie może być 1 metoda, kwestia tylko jak chcemy się dogadać co to znaku, że update się udał lub nie.

## Usuwanie
- Implementacja orderów później bedzie, wiec trzeba nowe issue, żeby o tym nie zapomnieć.
- Chcemy usuwać usera, czy oznaczać jako inactive, co uniemożliwi zalogowanie?
- Jeżeli wywalamy usera, to wszystkie powiązane z nim wpisy usuwamy? (np Historia transakcji)

**Comment by rukaSUKII** [comment]
@StanislawHornaGitHub 
> 
> ## Modyfikacja danych
> Dla mnie może być 1 metoda, kwestia tylko jak chcemy się dogadać co to znaku, że update się udał lub nie.
**Oznaczyć na pewno jakąś flagą success, ale wyznacznik tego czy update się udał to czy dane faktycznie się zmieniły w bazie. Więc trzeba by zrobić compare po update na bazie czy dane po select dla tego usera zgadzają się z danymi w message jakie było przesłane**


> ## Usuwanie
> * Implementacja orderów później bedzie, wiec trzeba nowe issue, żeby o tym nie zapomnieć ([Usuwanie pending orderów w trakcie usuwania / wyłączania konta użytkownika #9](https://github.com/THD-C/DB_Manager/issues/9) ).
**ok**

> * Chcemy usuwać usera, czy oznaczać jako inactive, co uniemożliwi zalogowanie?
**ja bym usuwał, bo tak to musielibyśmy kombinować ponownie przy rejestracji i logowaniu i całej logice, a nie mamy też jakby admina, żeby to konto reaktywować**

> * Jeżeli wywalamy usera, to wszystkie powiązane z nim wpisy usuwamy? (np Historia transakcji)
**dobra w sumie po przemyśleniu historia transakcji mogłaby zostać... Tylko wtedy robi nam się też problem przy integralności bazy jeśli transaction zostanie, a wszystko inne zostanie zrzucone**

**Comment by StanislawHornaGitHub** [comment]
@rukaSUKII 
Zrób proto tak jak to widzisz to ogarne DB_Managera
